main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('teachers/', views.teachers_index, name='index'),
  path('accounts/signup/', views.signup, name="signup"),
  path('teachers/<int:profile_id>/', views.profiles_detail, name='detail'), 
  path('teachers/<int:profile_id>/add_lesson/', views.add_lesson, name='add_lesson'),
  path('teachers/<int:profile_id>/add_photo/', views.add_photo, name='add_photo'),
  path('teachers/<int:profile_id>/delete_photo/', views.delete_photo, name='delete_photo'),
  path('lessons/<int:pk>/update/', views.LessonUpdate.as_view(), name='lessons_update'),
  path('lessons/<int:pk>/delete/', views.LessonDelete.as_view(), name='lessons_delete'),
  path('teachers/<int:pk>/update/', views.TeacherUpdate.as_view(), name='teachers_update'),
]

splashmusic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from embed_video.fields import EmbedVideoField

# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    is_teacher = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'profile_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for profile_id: {self.profile.id} @{self.url}"


# Default for CharField
class Lesson(models.Model):
    date = models.DateField()
    time = models.TimeField(default=timezone.now)
    instrument = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=250, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    video = models.CharField(max_length=250, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('detail', kwargs={ 'profile_id': self.profile.id })

class ModelName(models.Model):
    video = EmbedVideoField(blank=True)
    

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Lesson

class DateInput(forms.DateInput):
    input_type = 'date'

class LessonForm(ModelForm):
    class Meta:
        model = Lesson
        fields = ['date', 'time', 'instrument', 'description', 'video']
        widgets = {
            'date': DateInput(),
        }

main_app/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Profile, Lesson, Photo
from .forms import LessonForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'splash-music'

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form_data = request.POST.copy()
        is_teacher = request.POST.get('is_teacher', False) and True
        location = request.POST.get('location')
        bio = request.POST.get('bio')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        if 'is_teacher' in form_data:
            del form_data['is_teacher']
            del form_data['location']
            del form_data['bio']
        form = UserCreationForm(form_data)
        if form.is_valid():
            try:
                # This will add the user to the database
                user = form.save()
                Profile.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    is_teacher=is_teacher,
                    location=location,
                    bio=bio, user=user
                )
                # This is how we log a user in via code
                # Teachers index is showing students index
                login(request, user)
                return redirect('index')
            except Exception as err:
                print(err)
                error_message = 'Invalid sign up - try again'
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    return render(request, 'registration/signup.html', {'error_message': error_message})


def profiles_detail(request, profile_id):
    # We need to make student detail
    teacher = Profile.objects.get(id=profile_id)
    lesson_form = LessonForm()
    return render(request, 'teachers/detail.html', {
        'teacher': teacher,
        'lesson_form': lesson_form
    })


@login_required
def add_lesson(request, profile_id):
    form = LessonForm(request.POST)
    if form.is_valid():
        new_lesson = form.save(commit=False)
        new_lesson.profile_id = profile_id
        new_lesson.save()
    return redirect('detail', profile_id=profile_id)


class LessonCreateView(LoginRequiredMixin, CreateView):
    model = Lesson
    form_class = LessonForm


class LessonUpdate(LoginRequiredMixin, UpdateView):
    model = Lesson
    fields = ['date', 'time', 'instrument', 'description', 'video']


class LessonDelete(LoginRequiredMixin, DeleteView):
    model = Lesson


@login_required
def add_photo(request, profile_id):
    # photo-file will be the "name" attribute on the <input type="file"> used to upload the file
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for s3 / but keep the images extension
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something went wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, profile_id=profile_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', profile_id=profile_id)


@login_required
def delete_photo(request, profile_id):
    Photo.objects.get(profile_id=profile_id).delete()
    return redirect('detail', profile_id=profile_id)


def teachers_index(request):
    teachers = Profile.objects.all()
    return render(request, 'teachers/index.html', {'teachers': teachers})

    # def get_redirect_url(self):
    #   return f"/teachers/{self.user.id}"

    success_url = '/teachers'


class TeacherUpdate(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['first_name', 'last_name', 'location', 'bio']

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<section class="content" id="about">

  <h1>About Splash Music</h1>
  <p>Splash music was developed in 2021 by Galina, Michael, Martin and Jonah.</p>

</section>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
  <title>Splash Music</title>
</head>

<body>
  <header>
    <nav>
      <div id="top-nav">
        <div id="left-nav">
          <img src="/static/logo.png" alt="logo" id="nav-logo">
        <a href="{% url 'home' %}">
          <h2>Splash Music</h2>
        </a>
        </div>
        <ul id="right-nav">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'index' %}">All Instructors</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>

  <main class="container">

    {% block content %}
    {% endblock %}

  </main>

  <footer>
    <div id="footer">
      All Rights Reserved, &copy; 2021 Splash Music &nbsp
      <span id="favicon"><img src="{% static 'favicon.png' %}"></span>
    </div>
  </footer>

</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<section class="content" id="home">

  <h1>Welcome to Splash Music</h1>
  <p>
    Splash Music connects students of all ages and skill levels with musicians from the top music conservatories and ensembles in the
    world. Whether you’re a beginner or professional, our teachers will make sure you have the best online music experience.
  </p>
  <br>
  <p>
    {% if user.is_authenticated %}
      <a href="{% url 'index' %}" class="signup-btn"><button>Book A Lesson</button></a>
    {% else %}
      <a href="{% url 'signup' %}" class="signup-btn"><button>Book A Lesson</button></a>
    {% endif %}
  </p>

</section>

{% endblock %}

main_app/templates/main_app/lesson_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<section class="form" id="lesson-delete">

  <h1>Delete Lesson</h1>
  <p>Are you sure you want to delete this lesson?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="button-bar">
      <button type="submit">Delete</button> 
    </div>
  </form>
  <div class="button-bar">
    <a href="/teachers"><button>Instructors</button></a>
  </div>
</section>

{% endblock %}

main_app/templates/main_app/lesson_form.html
{% extends 'base.html' %}
{% block content %}

<section class="form" id="lesson-edit">
  <h1>Edit Lesson</h1>  
  <form action="" method="POST">
    {% csrf_token %}
      <table>
        {{ form }}
      </table>
      <div class="button-bar">
        <button type="submit">Save</button>
      </div>
  </form>  
  <a href="/teachers"><button>Cancel</button></a>  
</section>

{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}
{% block content %}

<section class="form" id="profile-edit">
  
  <h1>Edit Profile</h1>
  
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <div class="button-bar">
      <button type="submit">Save Changes</button>
    </div>
  </form>
  
  {% if object %} 
    <form action="{% url 'add_photo' profile.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <div class="button-bar">
        <button type="submit">Upload Photo</button>
      </div>
    </form>
  {% endif %}
<div class="button-bar">
  <a href="/"><button>Cancel</button></a>
</div>
</section>

{% endblock %}

main_app/templates/teachers/detail.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<section id="detail">

<div>
  <div>
    <h3>
      {{ teacher.first_name }}'s Lessons
    </h3>

    {% for photo in teacher.photo_set.all %}
      <img src="{{photo.url}}">
        {% if user.is_authenticated and user.id == teacher.user_id %}
          <form action="{% url 'delete_photo' photo.profile.id %}" method="POST">
            {% csrf_token %}
            <button type="submit">
              Delete Photo
            </button>
          </form>
        {% endif %}
    {% endfor %}

    <p>Email: <a href="mailto:{{ teacher.user }}">{{ teacher.user }}</a></p>
    <p>Location: {{ teacher.location }}</p>
    <p>Bio: {{ teacher.bio }}</p>

    {% if user.is_authenticated and user.id == teacher.user_id %}
      <a href="{% url 'teachers_update' teacher.id %}" style=' color:#3bba9c;'>Update Profile</a>

      {% if teacher.photo_set.all|length > 0 %}
      {% else %}
        <form action="{% url 'add_photo' teacher.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
       <div class='button-bar'>
        <button type="submit">Upload Photo</button>
       </div>
    </form>

      {% endif %}
    {% endif %}

    {% if user.is_authenticated %}
    <h3>Sign up for a lesson</h3>
      <form action="{% url 'add_lesson' teacher.id %}" method="POST">
        {% csrf_token %}
        <table>
          {{ lesson_form.as_table }}
        </table>
        <div class='button-bar'>
          <button type="submit">Submit</button>
        </div>
        <!-- <input type="submit" value="Add Lesson" class="btn"> -->
      </form>

      {% for lesson in teacher.lesson_set.all %}

      <div class="lesson-container">
        <div class="lesson-info">
          <p>
            {{ lesson.date }} | {{ lesson.time }} | {{ lesson.instrument }} | Extra Info: {{ lesson.description }}
          </p>
        </div>
        <div class="lesson-video">
          {% video lesson.video 'medium' %}
        </div>
        <div class="=button-bar">
          {% if user.id == lesson.profile.user_id %}
          <a href="{% url 'lessons_update' lesson.id %}"><button type="submit">Edit</button></a>
          <a href="{% url 'lessons_delete' lesson.id %}"><button type="submit">Delete</button></a>
          {% endif %}

        </div>
      </div>

      {% endfor %}

  </div>
</div>

  <p>
    {% else %}
    <a href="{% url 'signup' %}"><button>Book A Lesson</button></a>
  </p>

{% endif %}

{% endblock %}

main_app/templates/teachers/index.html
{% extends 'base.html' %}
{% block content %}

<section id="index">

  <h1>Our Instructors</h1>

  {% for teacher in teachers %}
  {% if teacher.is_teacher == True %}

    <div class="teacher-card">
      <a href="{% url 'detail' teacher.id %}">
        <div class="teacher-content">
          <img src="{{teacher.photo_set.first.url}}">
          <span class="card-title"> {{ teacher.name }} </span>
          <h2> {{ teacher.first_name }} {{ teacher.last_name }} </h2>
          <p>Location: {{ teacher.location }} </p>
          <p>Bio: {{ teacher.bio }} </p>
        </div>
      </a>
    </div>

  {% endif %}
  {% endfor %}

</section>

{% endblock %}